apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grr repo
  description: old repo
  tags:
    - java
    - frontend
  links:
    - url: https://github.com/shukilagama/grrr
      title: grr
      icon: github
spec:
  type: Repository
  lifecycle: lombelico
  owner: team-b
  system: podcast
